# Generated by Django 4.0.10 on 2023-12-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(max_length=10),
        ),
    ]
