# Generated by Django 4.0.10 on 2023-12-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_products_customuser_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
